language: ruby
sudo: false

rvm:
  - 2.0.0
  - 2.1.10
  - 2.2.7
  - 2.3.3
  - 2.4.0
  - ruby-head

gemfile:
  - gemfiles/Gemfile-rails.4.2.x
  - gemfiles/Gemfile-rails.5.0.x

matrix:
  exclude:
    - rvm: 2.0.0
      gemfile: gemfiles/Gemfile-rails.5.0.x
    - rvm: 2.1.10
      gemfile: gemfiles/Gemfile-rails.5.0.x
    - rvm: 2.4.0
      gemfile: gemfiles/Gemfile-rails.4.2.x
    - rvm: ruby-head
      gemfile: gemfiles/Gemfile-rails.4.2.x
