language: ruby

matrix:
  include:
    - rvm: 2.4.1
      gemfile: gemfiles/Gemfile-rails.5.1.x
    - rvm: 2.4.1
      gemfile: gemfiles/Gemfile-rails.5.0.x

    - rvm: 2.3.4
      gemfile: gemfiles/Gemfile-rails.5.1.x
    - rvm: 2.3.4
      gemfile: gemfiles/Gemfile-rails.5.0.x
    - rvm: 2.3.4
      gemfile: gemfiles/Gemfile-rails.4.2.x

    - rvm: 2.2.7
      gemfile: gemfiles/Gemfile-rails.5.1.x
    - rvm: 2.2.7
      gemfile: gemfiles/Gemfile-rails.5.0.x
    - rvm: 2.2.7
      gemfile: gemfiles/Gemfile-rails.4.2.x

    - rvm: 2.1.10
      gemfile: gemfiles/Gemfile-rails.4.2.x

    - rvm: 2.0.0
      gemfile: gemfiles/Gemfile-rails.4.2.x
